---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lew2547-test-redis-data
  labels:
    username: lew2547
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
